name: Build All Service Image

on:
  push:
    branches:
      - main
     
    

jobs:
  build-and-push-images-to-ECR:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

# AWS Credentials 
#================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

# Login to ECR
#=============
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      # Create repo if not exists
      #==========================
      - name: Create ECR repository if needed
        run: |
            repos=(
            accounting ad cart checkout currency email flagd flagd-ui fraud-detection
            frontend frontend-proxy grafana image-provider jaeger kafka llm
            load-generator opensearch otel-collector payment postgresql
            product-catalog product-reviews prometheus quote react-native-app
            recommendation shipping
            )

            for repo in "${repos[@]}"; do
            aws ecr describe-repositories --repository-names "$repo" >/dev/null 2>&1 \
            || aws ecr create-repository --repository-name "$repo"
            done


      - name: Build and push Docker images
        run: |
            # 1. Create the .env file from the GitHub Variable
            echo "${{ vars.ENV_FILE }}" | tr -d '\r' > .env

            # 2. Load the variables into the current shell session
            # This allows us to use $OTEL_JAVA_AGENT_VERSION etc. in the docker command
            export $(grep -v '^#' .env | xargs)

            services=(
              ad cart checkout currency email flagd flagd-ui fraud-detection
              frontend frontend-proxy grafana image-provider jaeger kafka llm
              load-generator opensearch otel-collector payment postgresql
              product-catalog product-reviews prometheus quote react-native-app
              recommendation shipping
            )

            export BUILD_ID=${GITHUB_RUN_NUMBER}

            for service in "${services[@]}"; do
              echo "------------------------------------------"
              echo "Processing service: $service"
              echo "------------------------------------------"

              # 3. Copy .env into the service folder so the Dockerfile can COPY it if needed
              cp .env "./src/$service/.env"

              # 4. Build with Build Args
              # We explicitly pass the version variables so the Dockerfile "ARG" lines can catch them
              docker build -t "$service:$BUILD_ID" \
                --build-arg "OTEL_JAVA_AGENT_VERSION=$OTEL_JAVA_AGENT_VERSION" \
                --build-arg "IMAGE_VERSION=$IMAGE_VERSION" \
                --build-arg "AD_PORT=$AD_PORT" \
                -f "./src/$service/Dockerfile" .

              # 5. Tag and Push
              docker tag "$service:$BUILD_ID" "${{ steps.login-ecr.outputs.registry }}/$service:$BUILD_ID"
              docker push "${{ steps.login-ecr.outputs.registry }}/$service:$BUILD_ID"
            done